### ISSUE TITLE
C63: Redirect to https with https-everywhere not working 

### ISSUE THREAD

**Issue by ltilve** [brave/muon#387]
When accessing to http://https-everywhere.badssl.com/ with the default settings (the extension is enabled) the browser should redirect automatically to https://https-everywhere.badssl.com/. The presence of HTTPS everywhere is detected, but the switch to https is not happening. 
The latest version of the extension seems to be properly working on upstream C63.

**Comment by ltilve** [comment]
It also seems that the page with ERR_CERT_DATE_INVALID is not being properly shown https://expired.badssl.com/
```An uncaught exception occurred in the main process Uncaught Exception:
TypeError: muonCb is not a function
    at App.app.on (/home/ltilve/brave/browser-laptop-bootstrap/src/browser-laptop/app/index.js:145:7)
    at emitMany (events.js:132:20)
    at App.emit (events.js:204:7)´´´

**Comment by ltilve** [comment]
For the particular case of the wrong `certificate-error` not being properly shown, @hferreiro already submitted a PR for `browser-laptop` https://github.com/brave/browser-laptop/pull/11998

**Comment by ltilve** [comment]
Fixed https://github.com/brave/browser-laptop/pull/11998#issuecomment-351921577
