### ISSUE TITLE
C66: crash happening on Linux

### ISSUE THREAD

**Issue by ltilve** [brave/muon#567]
When launching `66.0.3359.81` on Linux, we have been able to experiment some crash happening after some seconds starting the UI:
```
#0  0x00000000035e181e in service_manager::Connector::BindInterface(service_manager::Identity const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, mojo::ScopedHandleBase<mojo::MessagePipeHandle>) (this=0x0, target=..., interface_name=..., interface_pipe=...) at ../../services/service_manager/public/cpp/connector.cc:72
#1  0x0000000002c35b15 in service_manager::Connector::BindInterface<unzip::mojom::Unzipper>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, mojo::InterfaceRequest<unzip::mojom::Unzipper>) (this=0x0, name=..., request=...) at ../../services/service_manager/public/cpp/connector.h:120
#2  0x0000000002c35645 in unzip::Unzip(service_manager::Connector*, base::FilePath const&, base::FilePath const&, base::OnceCallback<void (bool)>) (connector=0x0, zip_path=..., output_dir=..., callback=...)
    at ../../components/unzip_service/public/cpp/unzip.cc:80
#3  0x0000000005c8f712 in update_client::ComponentUnpacker::BeginUnzipping() (this=<optimized out>) at ../../components/update_client/component_unpacker.cc:85
#4  0x0000000005c8f1d9 in update_client::ComponentUnpacker::Unpack(base::OnceCallback<void (update_client::ComponentUnpacker::Result const&)>) (this=0xb6403895480, callback=...) at ../../components/update_client/component_unpacker.cc:50
#5  0x0000000005c8d11a in update_client::(anonymous namespace)::StartInstallOnBlockingTaskRunner(scoped_refptr<base::SingleThreadTaskRunner>, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > const&, base::FilePath const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, scoped_refptr<update_client::CrxInstaller>, std::__1::unique_ptr<service_manager::Connector, std::__1::default_delete<service_manager::Connector> >, base::OnceCallback<void (int, int, int)>) (main_task_runner=..., pk_hash=..., crx_path=..., fingerprint=..., installer=..., connector=..., callback=...) at ../../components/update_client/component.cc:161
#6  0x0000000005c8e61a in base::internal::FunctorTraits<void (*)(scoped_refptr<base::SingleThreadTaskRunner>, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > const&, base::FilePath const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, scoped_refptr<update_client::CrxInstaller>, std::__1::unique_ptr<service_manager::Connector, std::__1::default_delete<service_manager::Connector> >, base::OnceCallback<void (int, int, int)>), void>::Invoke<scoped_refptr<base::SingleThreadTaskRunner>, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >, base::FilePath, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, scoped_refptr<update_client::CrxInstaller>, std::__1::unique_ptr<service_manager::Connector, std::__1::default_delete<service_manager::Connector> >, base::OnceCallback<void (int, int, int)> >(void (*)(scoped_refptr<base::SingleThreadTaskRunner>, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > const&, base::FilePath const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, scoped_refptr<update_client::CrxInstaller>, std::__1::unique_ptr<service_manager::Connector, std::__1::default_delete<service_manager::Connector> >, base::OnceCallback<void (int, int, int)>), scoped_refptr<base::SingleThreadTaskRunner>&&, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >&&, base::FilePath&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, scoped_refptr<update_client::CrxInstaller>&&, std::__1::unique_ptr<service_manager::Connector, std::__1::default_delete<service_manager::Connector> >&&, base::OnceCallback<void (int, int, int)>&&) (function=
    0x5c8d050 <update_client::(anonymous namespace)::StartInstallOnBlockingTaskRunner(scoped_refptr<base::SingleThreadTaskRunner>, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > const&, base::FilePath const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, scoped_refptr<update_client::CrxInstaller>, std::__1::unique_ptr<service_manager::Connector, std::__1::default_delete<service_manager::Connector> >, base::OnceCallback<void (int, int, int)>)>, args=<optimized out>, args=<unknown type in /home/ltilve/brave/66/browser-laptop-bootstrap/src/out/Release/brave, CU 0x95497181, DIE 0x954e2b51>, args=<unknown type in /home/ltilve/brave/66/browser-laptop-bootstrap/src/out/Release/brave, CU 0x95497181, DIE 0x954e2b61>, args=<unknown type in /home/ltilve/brave/66/browser-laptop-bootstrap/src/out/Release/brave, CU 0x95497181, DIE 0x954e2b71>, args=<optimized out>, args=<unknown type in /home/ltilve/brave/66/browser-laptop-bootstrap/src/out/Release/brave, CU 0x95497181, DIE 0x954e2b91>, args=<unknown type in /home/ltilve/brave/66/browser-laptop-bootstrap/src/out/Release/brave, CU 0x95497181, DIE 0x954e2ba1>) at ../../base/bind_internal.h:402
#7  0x0000000005c8e595 in base::internal::InvokeHelper<false, void>::MakeItSo<void (*)(scoped_refptr<base::SingleThreadTaskRunner>, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > const&, base::FilePath const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, scoped_refptr<update_client::CrxInstaller>, std::__1::unique_ptr<service_manager::Connector, std::__1::default_delete<service_manager::Connector> >, base::OnceCallback<void (int, int, int)>), scoped_refptr<base::SingleThreadTaskRunner>, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >, base::FilePath, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, scoped_refptr<update_client::CrxInstaller>, std::__1::unique_ptr<service_manager::Connector, std::__1::default_delete<service_manager::Connector> >, base::OnceCallback<void (int, int, int)> >(void (*&&)(scoped_refptr<base::SingleThreadTaskRunner>, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > const&, base::FilePath const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, scoped_refptr<update_client::CrxInstaller>, std::__1::unique_ptr<service_manager::Connector, std::__1::default_delete<service_manager::Connector> >, base::OnceCallback<void (int, int, int)>), scoped_refptr<base::SingleThreadTaskRunner>&&, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >&&, base::FilePath&&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&&, scoped_refptr<update_client::CrxInstaller>&&, std::__1::unique_ptr<service_manager::Connector, std::__1::default_delete<service_manager::Connector> >&&, base::OnceCallback<void (int, int, int)>&&) (functor=<optimized out>, args=<unknown type in /home/ltilve/brave/66/browser-laptop-bootstrap/src/out/Release/brave, CU 0x95497181, DIE 0x954ccb3f>, args=<unknown type in /home/ltilve/brave/66/browser-laptop-bootstrap/src/out/Release/brave, CU 0x95497181, DIE 0x954ccb48>, args=<unknown type in /home/ltilve/brave/66/browser-laptop-bootstrap/src/out/Release/brave, CU 0x95497181, DIE 0x954ccb51>, args=<unknown type in /home/ltilve/brave/66/browser-laptop-bootstrap/src/out/Release/brave, CU 0x95497181, DIE 0x954ccb5a>, args=<unknown type in /home/ltilve---Type <return> to continue, or q <return> to quit---
/brave/66/browser-laptop-bootstrap/src/out/Release/brave, CU 0x95497181, DIE 0x954ccb63>, args=<unknown type in /home/ltilve/brave/66/browser-laptop-bootstrap/src/out/Release/brave, CU 0x95497181, DIE 0x954ccb6c>, args=<unknown type in /home/ltilve/brave/66/browser-laptop-bootstrap/src/out/Release/brave, CU 0x95497181, DIE 0x954ccb75>) at ../../base/bind_internal.h:530
#8  0x0000000005c8e595 in base::internal::Invoker<base::internal::BindState<void (*)(scoped_refptr<base::SingleThreadTaskRunner>, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > const&, base::FilePath const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, scoped_refptr<update_client::CrxInstaller>, std::__1::unique_ptr<service_manager::Connector, std::__1::default_delete<service_manager::Connector> >, base::OnceCallback<void (int, int, int)>), scoped_refptr<base::SingleThreadTaskRunner>, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >, base::FilePath, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, scoped_refptr<update_client::CrxInstaller>, std::__1::unique_ptr<service_manager::Connector, std::__1::default_delete<service_manager::Connector> >, base::OnceCallback<void (int, int, int)> >, void ()>::RunImpl<void (*)(scoped_refptr<base::SingleThreadTaskRunner>, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > const&, base::FilePath const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, scoped_refptr<update_client::CrxInstaller>, std::__1::unique_ptr<service_manager::Connector, std::__1::default_delete<service_manager::Connector> >, base::OnceCallback<void (int, int, int)>), std::__1::tuple<scoped_refptr<base::SingleThreadTaskRunner>, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >, base::FilePath, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, scoped_refptr<update_client::CrxInstaller>, std::__1::unique_ptr<service_manager::Connector, std::__1::default_delete<service_manager::Connector> >, base::OnceCallback<void (int, int, int)> >, 0ul, 1ul, 2ul, 3ul, 4ul, 5ul, 6ul>(void (*&&)(scoped_refptr<base::SingleThreadTaskRunner>, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > const&, base::FilePath const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, scoped_refptr<update_client::CrxInstaller>, std::__1::unique_ptr<service_manager::Connector, std::__1::default_delete<service_manager::Connector> >, base::OnceCallback<void (int, int, int)>), std::__1::tuple<scoped_refptr<base::SingleThreadTaskRunner>, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >, base::FilePath, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, scoped_refptr<update_client::CrxInstaller>, std::__1::unique_ptr<service_manager::Connector, std::__1::default_delete<service_manager::Connector> >, base::OnceCallback<void (int, int, int)> >&&, std::__1::integer_sequence<unsigned long, 0ul, 1ul, 2ul, 3ul, 4ul, 5ul, 6ul>) (functor=<optimized out>, bound=<unknown type in /home/ltilve/brave/66/browser-laptop-bootstrap/src/out/Release/brave, CU 0x95497181, DIE 0x954ccb21>) at ../../base/bind_internal.h:604
#9  0x0000000005c8e595 in base::internal::Invoker<base::internal::BindState<void (*)(scoped_refptr<base::SingleThreadTaskRunner>, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> > const&, base::FilePath const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, scoped_refptr<update_client::CrxInstaller>, std::__1::unique_ptr<service_manager::Connector, std::__1::default_delete<service_manager::Connector> >, base::OnceCallback<void (int, int, int)>), scoped_refptr<base::SingleThreadTaskRunner>, std::__1::vector<unsigned char, std::__1::allocator<unsigned char> >, base::FilePath, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, scoped_refptr<update_client::CrxInstaller>, std::__1::unique_ptr<service_manager::Connector, std::__1::default_delete<service_manager::Connector> >, base::OnceCallback<void (int, int, int)> >, void ()>::RunOnce(base::internal::BindStateBase*) (base=<optimized out>) at ../../base/bind_internal.h:572
#10 0x0000000002f9a14d in base::OnceCallback<void ()>::Run() && (this=<optimized out>) at ../../base/callback.h:95
#11 0x0000000002f9a14d in base::debug::TaskAnnotator::RunTask(char const*, base::PendingTask*) (this=<optimized out>, queue_function=0x0, pending_task=0x7fff86ffd880) at ../../base/debug/task_annotator.cc:61
#12 0x0000000002ff07f0 in base::internal::TaskTracker::RunOrSkipTask(base::internal::Task, base::internal::Sequence*, bool) (this=<optimized out>, task=..., sequence=<optimized out>, can_run_task=<optimized out>)
    at ../../base/task_scheduler/task_tracker.cc:460
#13 0x0000000002ff1623 in base::internal::TaskTrackerPosix::RunOrSkipTask(base::internal::Task, base::internal::Sequence*, bool) (this=0x7ffff7e86ea0, task=..., sequence=0x7fff86ffd200, can_run_task=32) at ../../base/task_scheduler/task_tracker_posix.cc:25
#14 0x0000000002ff0165 in base::internal::TaskTracker::RunAndPopNextTask(scoped_refptr<base::internal::Sequence>, base::internal::CanScheduleSequenceObserver*) (this=0x7ffff7e86ea0, sequence=..., observer=<optimized out>)
    at ../../base/task_scheduler/task_tracker.cc:353
#15 0x0000000002fedbcc in base::internal::SchedulerWorker::Thread::ThreadMain() (this=0xb6403dc21b0) at ../../base/task_scheduler/scheduler_worker.cc:85
#16 0x0000000002ffa8ed in base::(anonymous namespace)::ThreadFunc(void*) (params=0xb6403dc3b20) at ../../base/threading/platform_thread_posix.cc:76
#17 0x00007ffff7bc15aa in start_thread (arg=0x7fff86ffe700) at pthread_create.c:463
#18 0x00007ffff1f32cbf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by ltilve** [comment]
Fixed by https://github.com/brave/muon/commit/7fdcb483522fbff503538ba5c6d6d623861b301e
